fail_fast: false
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg, post-commit]
repos:
  - repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
      - id: commit-msg-regex-hook
        args: ["--pattern='\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'", "--failure_message=\tCommits need to mention a JIRA ticket, version impact and \n\ta description, e.g.: '[ABC-123][minor]: message' \n\tRegex:'\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'"]
        stages: [commit-msg]
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: ["--batch-mode clean package"]
        stages: [post-commit]
      # Code quality
      - id: maven
        args: ["--batch-mode spotbugs:spotbugs"]
      - id: maven
        args: ["--batch-mode spotless:check"]
