repos:
  - repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
      - id: commit-msg-regex-hook
        args:
          [
            "--pattern='\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'",
            "--failure_message='Commits should match the pattern (including brackets): [ABC-123][minor]: message here'",
          ]
        stages: [commit-msg]
