- &defaults
  fail_fast: false
  default_install_hook_types: [pre-commit, commit-msg, post-commit]
- &commit-msg
  repo: https://github.com/dtaivpp/commit-msg-regex-hook
  rev: v0.2.1
  hooks:
  - id: commit-msg-regex-hook
    args: ["--pattern='\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'", "--failure_message=\tCommits need to mention a JIRA ticket, version impact and \n\ta description, e.g.: '[ABC-123][minor]: message' \n\tRegex:'\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'"]
    stages: [commit-msg]
- &java-maven
  repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.3
  hooks:
  - id: maven
    args: ["--batch-mode clean package"]
    stages: [post-commit]
  - id: maven
    args: ["--batch-mode spotbugs:spotbugs"]
    stages: [pre-commit]
  - id: maven
    args: ["--batch-mode spotless:check"]
    stages: [pre-commit]
- &kotlin-maven
  repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.3
  hooks:
  - id: maven
    args: ["--batch-mode clean package"]
    stages: [post-commit]
  - id: maven
    args: ["--batch-mode diktat:check@diktat"]
    stages: [pre-commit]
- &java-gradle
  repo: https://github.com/jguttman94/pre-commit-gradle
  rev: v0.3.0
  hooks:
  - id: gradle-task
    args: ['spotlessCheck', '-w', '-o']
    stages: [pre-commit]
  - id: gradle-build
    args: ['-w', '-o']
    stages: [post-commit]
  - id: gradle-task
    args: ['spotbugsMain', '-w', '-o']
    stages: [pre-commit]
- &kotlin-gradle
  repo: https://github.com/jguttman94/pre-commit-gradle
  rev: v0.3.0
  hooks:
  - id: gradle-build
    args: ['-w', '-o']
    stages: [post-commit]

---
!!merge <<: *defaults
repos:
- !!merge <<: *commit-msg
- !!merge <<: *java-maven
---
!!merge <<: *defaults
repos:
- !!merge <<: *commit-msg
- !!merge <<: *kotlin-maven
---
!!merge <<: *defaults
repos:
- !!merge <<: *commit-msg
- !!merge <<: *java-gradle
---
!!merge <<: *defaults
repos:
- !!merge <<: *commit-msg
- !!merge <<: *kotlin-gradle
