.defaults: &defaults
  fail_fast: false
  default_install_hook_types: [pre-commit, commit-msg, post-commit]
steps:
- &commit-msg
  repo: https://github.com/dtaivpp/commit-msg-regex-hook
  rev: v0.2.1
  hooks:
  - id: commit-msg-regex-hook
    args: ["--pattern='\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'", "--failure_message=\tCommits need to mention a JIRA ticket, version impact and \n\ta description, e.g.: '[ABC-123][minor]: message' \n\tRegex:'\\[[A-Z]{2,4}-\\d+\\]\\[(major|minor|patch)\\]\\:\\s\\w+'"]
    stages: [commit-msg]
- &java-maven
  repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.3
  hooks:
  - id: maven
    args: ["--batch-mode clean package"]
    stages: [post-commit]
  - id: maven
    args: ["--batch-mode spotbugs:spotbugs"]
    stages: [pre-commit]
  - id: maven
    args: ["--batch-mode spotless:check"]
    stages: [pre-commit]
- &kotlin-maven
  repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.3
  hooks:
  - id: maven
    args: ["--batch-mode clean package"]
    stages: [post-commit]
  - id: maven
    args: ["--batch-mode diktat:check@diktat"]
    stages: [pre-commit]
- &java-gradle
  repo: https://github.com/jguttman94/pre-commit-gradle
  rev: v0.3.0
  hooks:
  - id: gradle-task
    args: ['spotlessCheck', '-w', '-o']
    stages: [pre-commit]
  - id: gradle-build
    args: ['-w', '-o']
    stages: [post-commit]
  - id: gradle-task
    args: ['spotbugsMain', '-w', '-o']
    stages: [pre-commit]
- &kotlin-gradle
  repo: https://github.com/jguttman94/pre-commit-gradle
  rev: v0.3.0
  hooks:
  - id: gradle-build
    args: ['-w', '-o']
    stages: [post-commit]
- &javascript
  repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0 # Replace with the desired version of Prettier
  hooks:
  - id: prettier
    entry: prettier --check
    types_or: [javascript, ts]
    stages: [pre-commit]
- &tf-tfsec
  repo: https://github.com/liamg/tfsec # Security Checks
  rev: v1.28.1
  hooks:
  - id: tfsec
    description: This hook runs tfsec scan.
    entry: tfsec
- &tf-checkov
  repo: https://github.com/bridgecrewio/checkov
  rev: 2.4.6
  hooks:
  - id: checkov
    name: Checkov
    description: This hook runs checkov scan.
    entry: checkov -d . --quiet
- &tf-pre-commit-terraform
  repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.82.0
  hooks:
  - id: terraform_validate # Code Quality check
    description: This hook runs "terraform validate" scan.
  - id: terraform_fmt # Code Styling check
    description: This hook runs "terraform fmt -recursive" scan.
    args:
    - --args=-recursive
    - --args=-write=false
  - id: terraform_tflint
    description: This hook runs tflint scan.
---
<<: *defaults
repos:
- *commit-msg
- *java-maven
---
<<: *defaults
repos:
- *commit-msg
- *kotlin-maven
---
<<: *defaults
repos:
- *commit-msg
- *java-gradle
---
<<: *defaults
repos:
- *commit-msg
- *kotlin-gradle
---
<<: *defaults
repos:
- *commit-msg
- *javascript
---
<<: *defaults
repos:
- *commit-msg
- *tf-tfsec
- *tf-checkov
- *tf-pre-commit-terraform
