default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg, post-commit]
repos:
  - repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
      - id: commit-msg-regex-hook
        name: Validate commit message format
        args: ["--pattern='\\[\\b[A-Z][A-Z0-9_]+-[1-9][0-9]*\\]\\[(major|minor|patch)\\]\\:\\s\\w+'", "--failure_message=\tCommits need to mention a JIRA ticket, version impact and \n\ta description, e.g.: '[ABC-123][minor]: message' \n\tRegex:'\\[\\b[A-Z][A-Z0-9_]+-[1-9][0-9]*\\]\\[(major|minor|patch)\\]\\:\\s\\w+'"]
        stages: [commit-msg]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      # Detect secrets
      - id: gitleaks
        name: Check for secrets being committed
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Replace with the desired version of Prettier
    hooks:
      # Code styling check
      - id: prettier
        name: Check using Prettier
        entry: prettier --check
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.48.0' # Replace with the desired version of ESlint
    hooks:
      # Code Quality check
      - id: eslint
        name: Check using ESLint
        files: \.[jt]sx?$ # For *.js, *.jsx, *.ts and *.tsx
        additional_dependencies: # Add the required additional dependencies.
          - eslint@latest
          - eslint-plugin-react@latest
          - '@typescript-eslint/parser@latest'
          - '@typescript-eslint/eslint-plugin@latest'
