default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg, post-commit]
repos:
  - repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
      - id: commit-msg-regex-hook
        name: Validate commit message format
        args: ["--pattern='\\[\\b[A-Z][A-Z0-9_]+-[1-9][0-9]*\\]\\[(major|minor|patch)\\]\\:\\s\\w+'", "--failure_message=\tCommits need to mention a JIRA ticket, version impact and \n\ta description, e.g.: '[ABC-123][minor]: message' \n\tRegex:'\\[\\b[A-Z][A-Z0-9_]+-[1-9][0-9]*\\]\\[(major|minor|patch)\\]\\:\\s\\w+'"]
        stages: [commit-msg]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      # Detect secrets
      - id: gitleaks
        name: Check for secrets being committed
  - repo: https://github.com/liamg/tfsec
    rev: v1.28.1
    hooks:
      # Security Checks
      - id: tfsec
        name: Scan using tfsec
        description: This hook runs tfsec scan.
        entry: tfsec
  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.4.6
    hooks:
      - id: checkov
        name: Checkov
        description: This hook runs checkov scan.
        entry: checkov -d . --quiet
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      # Code Quality check
      - id: terraform_validate
        name: terraform validate
        description: This hook runs "terraform validate" scan.
      # Code Styling check
      - id: terraform_fmt
        name: terraform format
        description: This hook runs "terraform fmt -recursive" scan.
        args:
          - --args=-recursive
          - --args=-write=false
      - id: terraform_tflint
        description: This hook runs tflint scan.
